---
#######system variables############
region: SJ
interface_net: 192.168.24.0/24

#######ceph config#################
ceph_type: ssd
##########zabbix###################
#######zabbix-agent#############
zabbix_agent_server: 192.168.68.127
zabbix_agent_script:
  - disk_io_discovery.py
  - disk_io_status.sh
  - zabbix-docker.py
######Zabbix API stuff##########
zabbix_url: http://192.168.68.121/zabbix/
zabbix_api_user: zhaobinwei
zabbix_api_pass: DIn4ro3jmENO
zabbix_proxy: zabbix_proxy_sj
zabbix_host_groups: 松江-new
zabbix_link_templates:
  - Template App Docker
  - base OS Linux_openstack
